# 张量简介

In [1]:
import tensorflow as tf
import numpy as np

张量是具有统一类型（称为 `dtype`）的多维数组。您可以在 `tf.dtypes.DType` 中查看所有支持的 `dtypes`。

如果您熟悉 [NumPy](https://numpy.org/devdocs/user/quickstart.html)，就会知道张量与 `np.arrays` 有一定的相似性。

就像 Python 数值和字符串一样，所有张量都是不可变的：永远无法更新张量的内容，只能创建新的张量。


## 基础知识

我们来创建一些基本张量。

下面是一个“标量”（或称“0 秩”张量）。标量包含单个值，但没有“轴”。

In [2]:
# 默认情况下，这将是一个 int32 张量；请参阅下面的“dtypes”。
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


> `tf.constant()`: 从类似张量的对象创建一个常量张量。
> ```python
> tf.constant(
>     value, dtype=None, shape=None, name='Const'
> )
> ```

“向量”（或称“1 秩”张量）就像一个值列表。向量有 1 个轴：

In [3]:
# 让我们把它变成一个浮点张量。
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


“矩阵”（或称“2 秩”张量）有 2 个轴：

In [4]:
# 如果我们想具体一点，我们可以在创建时设置 dtype（见下文）
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


<table>
<tr>
  <th>标量，形状：<code>[]</code> </th>
  <th>向量，形状：<code>[3]</code> </th>
  <th>矩阵，形状：<code>[3, 2]</code> </th>
</tr>
<tr>
  <td>    <img src="https://tensorflow.google.cn/guide/images/tensor/scalar.png" alt="A scalar, the number 4"> </td>
  <td>    <img src="https://tensorflow.google.cn/guide/images/tensor/vector.png" alt="The line with 3 sections, each one containing a number."> </td>
  <td>    <img src="https://tensorflow.google.cn/guide/images/tensor/matrix.png" alt="A 3x2 grid, with each cell containing a number."> </td>
</tr>
</table>


张量的轴可能更多，下面是一个包含 3 个轴的张量：

In [5]:
# 可以有任意数量的轴(有时称为“维度(dimensions)”)
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
                    
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


对于包含 2 个以上的轴的张量，您可以通过多种方式加以呈现。

<table>
<tr>
  <th colspan="3">3 轴张量，形状：<code>[3, 2, 5]</code> </th>
</tr>
<tr>
</tr>
<tr>
  <td>    <img src="https://tensorflow.google.cn/guide/images/tensor/3-axis_numpy.png"> </td>
  <td>    <img src="https://tensorflow.google.cn/guide/images/tensor/3-axis_front.png"> </td>
  <td>    <img src="https://tensorflow.google.cn/guide/images/tensor/3-axis_block.png"> </td>
</tr>
</table>

通过使用 `np.array` 或 `tensor.numpy` 方法，您可以将张量转换为 NumPy 数组：

In [6]:
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [8]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

张量通常包含浮点型和整型数据，但是还有许多其他数据类型，包括：

- 复杂的数值
- 字符串

`tf.Tensor` 基类要求张量是“矩形”——也就是说，每个轴上的每一个元素大小相同。但是，张量有可以处理不同形状的特殊类型。

- 不规则张量（参阅下文中的 [RaggedTensor](#ragged_tensors)）
- 稀疏张量（参阅下文中的 [SparseTensor](#sparse_tensors)）

您可以对张量执行基本数学运算，包括加法、逐元素乘法和[矩阵乘法](https://baike.baidu.com/item/%E7%9F%A9%E9%98%B5%E4%B9%98%E6%B3%95/5446029)。

In [12]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # 也可以说 `tf.ones([2,2])`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
# 矩阵乘法(matrix multiplication)
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [13]:
print(a + b, "\n") # 逐元素加法
print(a * b, "\n") # 逐元素乘法
print(a @ b, "\n") # 矩阵乘法(matrix multiplication)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



- [`tf.add(x, y)`](https://www.tensorflow.org/api_docs/python/tf/math/add): x + y, 若一个是张量，一个是非张量，则结果为张量
    ```python
    tf.math.add(
        x, y, name=None
    )
    ```
- [`tf.multiply(a, b)`](https://www.tensorflow.org/api_docs/python/tf/math/multiply): a * b
    ```python
    tf.math.multiply(
        x, y, name=None
    )
    ```
- [`tf.matmul(a, b)`](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul): 将矩阵 a 与矩阵 b 相乘，得到 a * b

各种运算 (op) 都可以使用张量。

In [17]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])
print(c)

# 找到最大值
print(tf.reduce_max(c))
# 找到最大值的索引
print(tf.argmax(c))
# 计算softmax(Compute the softmax)
print(tf.nn.softmax(c))

tf.Tensor(
[[ 4.  5.]
 [10.  1.]], shape=(2, 2), dtype=float32)
tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


- [`tf.reduce_max(x)`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_max): 计算跨张量维度的元素的[最大值(`tf.math.maximum`)](https://www.tensorflow.org/api_docs/python/tf/math/maximum)
- [`tf.argmax(c)`](https://www.tensorflow.org/api_docs/python/tf/math/argmax): 返回张量轴上具有最大值的索引
- [`tf.nn.softmax(c)`](https://www.tensorflow.org/api_docs/python/tf/nn/softmax): 计算 softmax, 用于多类预测。softmax 生成的所有输出的总和为 1。 此函数执行等效于 `softmax = tf.exp(logits) / tf.reduce_sum(tf.exp(logits), axis)`
- [`tf.math.exp(x)`](https://www.tensorflow.org/api_docs/python/tf/math/exp): 计算 x 元素的指数. \\(y = e^x\\)
- [`tf.reduce_sum(x)`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum): 计算张量维度上的元素总和

## 形状简介

张量有形状。下面是几个相关术语：

- **形状**：张量的每个轴的长度（元素数量）。
- **秩**：张量轴数。标量的秩为 0，向量的秩为 1，矩阵的秩为 2。
- **轴**或**维度**：张量的一个特殊维度。
- **大小**：张量的总项数，即乘积形状向量


注：虽然您可能会看到“二维张量”之类的表述，但 2 秩张量通常并不是用来描述二维空间。

张量和 `tf.TensorShape` 对象提供了方便的属性来访问：

In [27]:
# 4 纬(四秩张量)
rank_4_tensor = tf.zeros([3, 2, 4, 5])

<table>
<tr>
  <th colspan="2">4 秩张量，形状：<code>[3, 2, 4, 5]</code> </th>
</tr>
<tr>
  <td> <img src="https://tensorflow.google.cn/guide/images/tensor/shape.png" alt="A tensor shape is like a vector."> </td>
<td> <img src="https://tensorflow.google.cn/guide/images/tensor/4-axis_block.png" alt="A 4-axis tensor"> </td>
  </tr>
</table>


In [21]:
print("每个元素的类型:", rank_4_tensor.dtype)
print("维数:", rank_4_tensor.ndim)
print("张量的形状(每个轴的长度):", rank_4_tensor.shape)
print("沿张量第一个轴的元素:", rank_4_tensor.shape[0])
print("沿张量最后一个轴的元素:", rank_4_tensor.shape[-1])
print("元素总数(3*2*4*5): ", tf.size(rank_4_tensor).numpy())

每个元素的类型: <dtype: 'float32'>
维数: 4
张量的形状(每个轴的长度): (3, 2, 4, 5)
沿张量第一个轴的元素: 3
沿张量最后一个轴的元素: 5
元素总数(3*2*4*5):  120


- [`tf.zeros([3, 2, 4, 5])`](https://www.tensorflow.org/api_docs/python/tf/zeros): 创建一个所有元素都设置为零的张量

虽然通常用索引来指代轴，但是您始终要记住每个轴的含义。轴一般按照从全局到局部的顺序进行排序：首先是批次轴，随后是空间维度，最后是每个位置的特征。这样，在内存中，特征向量就会位于连续的区域。

<table>
<tr>
<th>典型的轴顺序</th>
</tr>
<tr>
    <td> <img src="https://tensorflow.google.cn/guide/images/tensor/shape2.png" alt="Keep track of what each axis is. A 4-axis tensor might be: Batch, Width, Height, Features"> </td>
</tr>
</table>

## 索引

### 单轴索引

TensorFlow 遵循标准 Python 索引规则（类似于[在 Python 中为列表或字符串编制索引](https://docs.python.org/3/tutorial/introduction.html#strings)）以及 NumPy 索引的基本规则。

- 索引从 `0` 开始编制
- 负索引表示按倒序编制索引
- 冒号 `:` 用于切片 `start:stop:step`


In [28]:
# 一维(一秩张量)
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


使用标量编制索引会移除轴：

In [24]:
print("第一个:", rank_1_tensor[0].numpy())
print("第二个:", rank_1_tensor[1].numpy())
print("最后一个:", rank_1_tensor[-1].numpy())

第一个: 0
第二个: 1
最后一个: 34


使用 `:` 切片编制索引会保留轴：

In [25]:
print("所有:", rank_1_tensor[:].numpy())
print("前 4:", rank_1_tensor[:4].numpy())
print("从 4(第 5 个) 到结束:", rank_1_tensor[4:].numpy())
print("从 2(第 3 个) 到 7 之前:", rank_1_tensor[2:7].numpy())
print("所有的按步长 2 取值(每 2 个取第 1 个):", rank_1_tensor[::2].numpy())
print("反转:", rank_1_tensor[::-1].numpy())

所有: [ 0  1  1  2  3  5  8 13 21 34]
前 4: [0 1 1 2]
从 4(第 5 个) 到结束: [ 3  5  8 13 21 34]
从 2(第 3 个) 到 7 之前: [1 2 3 5 8]
所有的按步长 2 取值(每 2 个取第 1 个): [ 0  1  3  8 21]
反转: [34 21 13  8  5  3  2  1  1  0]


### 多轴索引

更高秩的张量通过传递多个索引来编制索引。

对于高秩张量的每个单独的轴，遵循与单轴情形完全相同的规则。

In [29]:
# 二维(二秩张量)
print(rank_2_tensor.numpy())

[[1. 2.]
 [3. 4.]
 [5. 6.]]


为每个索引传递一个整数，结果是一个标量。

In [30]:
# 从 2 秩张量中提取单个值
print(rank_2_tensor[1, 1].numpy())

4.0


您可以使用整数与切片的任意组合编制索引：

In [31]:
# 获取行和列张量
print("第二行:", rank_2_tensor[1, :].numpy())
print("第二列:", rank_2_tensor[:, 1].numpy())
print("最后一行:", rank_2_tensor[-1, :].numpy())
print("最后一列的第一个:", rank_2_tensor[0, -1].numpy())
print("跳过第一行:")
print(rank_2_tensor[1:, :].numpy(), "\n")

第二行: [3. 4.]
第二列: [2. 4. 6.]
最后一行: [5. 6.]
最后一列的第一个: 2.0
跳过第一行:
[[3. 4.]
 [5. 6.]] 



下面是一个 3 轴张量的示例：

In [32]:
# 三维(三秩张量 或 3 轴张量)
print(rank_3_tensor[:, :, 4])

tf.Tensor(
[[ 4  9]
 [14 19]
 [24 29]], shape=(3, 2), dtype=int32)


<table>
<tr>
<th colspan="2">选择批次中每个示例的所有位置的最后一个特征</th>
</tr>
<tr>
    <td> <img src="https://tensorflow.google.cn/guide/images/tensor/index1.png" alt="A 3x2x5 tensor with all the values at the index-4 of the last axis selected."> </td>
      <td> <img src="https://tensorflow.google.cn/guide/images/tensor/index2.png" alt="The selected values packed into a 2-axis tensor."> </td>
</tr>
</table>

请参阅[张量切片指南](https://tensorflow.org/guide/tensor_slicing)，了解如何应用索引编制以操作张量中的各个元素。

## 操作形状

重构(Reshape)张量非常有用。

In [35]:
# shape 返回一个 `TensorShape` 对象，显示每个维度的大小
var_x = tf.Variable(tf.constant([[1], [2], [3]]))
print(var_x.shape)

(3, 1)


In [36]:
# 您也可以将此对象转换为 Python 列表
print(var_x.shape.as_list())

[3, 1]


通过重构可以改变张量的形状。重构的速度很快，资源消耗很低，因为不需要复制底层数据。

In [39]:
# 我们可以将张量重构为新形状。将形状从 (3, 1) 重构为 (1, 3)
# 请注意，我们正在传入(passing in)一个列表
reshaped = tf.reshape(var_x, [1, 3])

In [40]:
print(var_x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


数据在内存中的布局保持不变，同时使用请求的形状创建一个指向同一数据的新张量。TensorFlow 采用 C 样式的“行优先”内存访问顺序，即最右侧的索引值递增对应于内存中的单步位移。

In [41]:
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


如果您展平张量，则可以看到它在内存中的排列顺序。

In [42]:
# 在 `shape` 参数中传入(passed in)的 `-1` 表示“任何适合(Whatever fits)”。
print(tf.reshape(rank_3_tensor, [-1]))

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)


一般来说，`tf.reshape` 唯一合理的用途是用于合并或拆分相邻轴（或添加/移除 `1`）。

对于 3x2x5 张量，重构为 (3x2)x5 或 3x(2x5) 都合理，因为切片不会混淆：

In [43]:
print(tf.reshape(rank_3_tensor, [3*2, 5]), "\n")
print(tf.reshape(rank_3_tensor, [3, -1]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


<table>
<th colspan="3">一些正确的重构示例。</th>
<tr>
  <td> <img src="https://tensorflow.google.cn/guide/images/tensor/reshape-before.png" alt="A 3x2x5 tensor"> </td>
  <td>   <img src="https://tensorflow.google.cn/guide/images/tensor/reshape-good1.png" alt="The same data reshaped to (3x2)x5"> </td>
  <td> <img src="https://tensorflow.google.cn/guide/images/tensor/reshape-good2.png" alt="The same data reshaped to 3x(2x5)"> </td>
</tr>
</table>


重构可以处理总元素个数相同的任何新形状，但是如果不遵从轴的顺序，则不会发挥任何作用。

利用 `tf.reshape` 无法实现轴的交换，要交换轴，您需要使用 `tf.transpose`。


In [46]:
# 反例：不要这样做

# 您不能使用 reshape 对轴重新排序
print(tf.reshape(rank_3_tensor, [2, 3, 5]), "\n") 

# 这是一团糟
print(tf.reshape(rank_3_tensor, [5, 6]), "\n")

# 这根本不起作用
try:
  tf.reshape(rank_3_tensor, [7, -1])
except Exception as e:
  print(f"{type(e).__name__}: {e}")

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]], shape=(2, 3, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]], shape=(5, 6), dtype=int32) 

InvalidArgumentError: Input to reshape is a tensor with 30 values, but the requested shape requires a multiple of 7 [Op:Reshape]


<table>
<th colspan="3">一些错误的重构示例。</th>
<tr>
  <td> <img src="https://tensorflow.google.cn/guide/images/tensor/reshape-bad.png" alt="You can't reorder axes, use tf.transpose for that"> </td>
  <td><img src="https://tensorflow.google.cn/guide/images/tensor/reshape-bad4.png" alt="Anything that mixes the slices of data together is probably wrong."></td>
  <td> <img src="https://tensorflow.google.cn/guide/images/tensor/reshape-bad2.png" alt="The new shape must fit exactly."> </td>
</tr>
</table>

您可能会遇到非完全指定的形状。要么是形状包含 `None`（轴长度未知），要么是整个形状为 `None`（张量的秩未知）。

除了 [tf.RaggedTensor](#ragged_tensors) 外，这种情况只会在 TensorFlow 的符号化计算图构建 API 环境中出现：

- [tf.function](function.ipynb)
- [Keras 函数式 API](keras/functional.ipynb)。


## `DTypes` 详解

使用 `Tensor.dtype` 属性可以检查 `tf.Tensor` 的数据类型。

从 Python 对象创建 `tf.Tensor` 时，您可以选择指定数据类型。

如果不指定，TensorFlow 会选择一个可以表示您的数据的数据类型。TensorFlow 将 Python 整数转换为 `tf.int32`，将 Python 浮点数转换为 `tf.float32`。另外，当转换为数组时，TensorFlow 会采用与 NumPy 相同的规则。

数据类型可以相互转换。

In [47]:
the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64)
the_f16_tensor = tf.cast(the_f64_tensor, dtype=tf.float16)
# 现在，让我们转换为 uint8 并失去小数精度(decimal precision)
the_u8_tensor = tf.cast(the_f16_tensor, dtype=tf.uint8)
print(the_u8_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=uint8)


## 广播

广播是从 [NumPy 中的等效功能](https://numpy.org/doc/stable/user/basics.html)借用的一个概念。简而言之，在一定条件下，对一组张量执行组合运算时，为了适应大张量，会对小张量进行“扩展”。

最简单和最常见的例子是尝试将张量与标量相乘或相加。在这种情况下会对标量进行广播，使其变成与其他参数相同的形状。 

In [48]:
x = tf.constant([1, 2, 3])

y = tf.constant(2)
z = tf.constant([2, 2, 2])
# 所有这些都是相同的计算
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


同样，可以扩展长度为 1 的轴，使其匹配其他参数。在同一个计算中可以同时扩展两个参数。

在本例中，一个 3x1 的矩阵与一个 1x4 进行元素级乘法运算，从而产生一个 3x4 的矩阵。注意前导 1 是可选的：y 的形状是 `[4]`。

In [49]:
# 这些是相同的计算
x = tf.reshape(x,[3,1])
y = tf.range(1, 5)
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


<table>
<tr>
  <th>广播相加：<code>[3, 1]</code> 乘以 <code>[1, 4]</code> 的结果是 <code>[3,4]</code> </th>
</tr>
<tr>
  <td> <img src="https://tensorflow.google.cn/guide/images/tensor/broadcasting.png" alt="Adding a 3x1 matrix to a 4x1 matrix results in a 3x4 matrix"> </td>
</tr>
</table>

- [`tf.range()`](https://www.tensorflow.org/api_docs/python/tf/range): 创建一个数字序列
    - `tf.range(limit, delta=1, dtype=None, name='range')`
    - `tf.range(start, limit, delta=1, dtype=None, name='range')`

下面是不使用广播的同一运算：

In [50]:
x_stretch = tf.constant([[1, 1, 1, 1],
                         [2, 2, 2, 2],
                         [3, 3, 3, 3]])

y_stretch = tf.constant([[1, 2, 3, 4],
                         [1, 2, 3, 4],
                         [1, 2, 3, 4]])

print(x_stretch * y_stretch)  # 再次运算符重载

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


在大多数情况下，广播的时间和空间效率更高，因为广播运算不会在内存中具体化扩展的张量。

使用 `tf.broadcast_to` 可以了解广播的运算方式。

In [51]:
# 展示将 1x3 的张量扩展成 3x3 的形状
print(tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


与数学运算不同，[`broadcast_to`](https://www.tensorflow.org/api_docs/python/tf/broadcast_to) 并不会节省内存。在这个示例中，您将具体化张量。

这可能会变得更复杂。Jake VanderPlas 的<em>《Python 数据科学手册》</em>一书中的[这一节](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)介绍了更多广播技巧（同样使用 NumPy）。

## [tf.convert_to_tensor](https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor)

将给定值转换为张量

大部分运算（如 `tf.matmul` 和 `tf.reshape`）会使用 [`tf.Tensor`](https://www.tensorflow.org/api_docs/python/tf/Tensor) 类的参数。不过，在上面的示例中，您会发现形状类似于张量的 Python 对象也可以接受。

大部分（但并非全部）运算会在非张量参数上调用 `convert_to_tensor`。我们提供了一个转换注册表，大多数对象类（如 NumPy 的 `ndarray`、`TensorShape`、Python 列表和 `tf.Variable`）都可以自动转换。

有关更多详细信息，请参阅 [`tf.register_tensor_conversion_function`](https://www.tensorflow.org/api_docs/python/tf/register_tensor_conversion_function)。如果您有自己的类型，则可能希望自动转换为张量。

## 不规则张量

如果张量的某个轴上的元素个数可变，则称为“不规则”张量。对于不规则数据，请使用 `tf.ragged.RaggedTensor`。

例如，下面的例子无法用规则张量表示：

<table>
<tr>
  <th>“tf.RaggedTensor”，形状：<code>[4, None]</code> </th>
</tr>
<tr>
  <td> <img src="https://tensorflow.google.cn/guide/images/tensor/ragged.png" alt="A 2-axis ragged tensor, each row can have a different length."> </td>
</tr>
</table>

In [52]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

In [53]:
try:
  tensor = tf.constant(ragged_list)
except Exception as e:
  print(f"{type(e).__name__}: {e}")

ValueError: Can't convert non-rectangular Python sequence to Tensor.


应使用 [`tf.ragged.constant`](https://www.tensorflow.org/api_docs/python/tf/ragged/constant) 来创建 [`tf.RaggedTensor`](https://www.tensorflow.org/api_docs/python/tf/RaggedTensor)：

In [54]:
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


`tf.RaggedTensor` 的形状将包含一些具有未知长度的轴：

In [55]:
print(ragged_tensor.shape)

(4, None)


## 字符串张量

[`tf.string`](https://www.tensorflow.org/api_docs/python/tf#string) 是一种 `dtype`，也就是说，在张量中，您可以用字符串（可变长度字节数组）来表示数据。

字符串是原子类型，无法像 Python 字符串一样编制索引。字符串的长度并不是张量的一个轴。有关操作字符串的函数，请参阅 [`tf.strings`](https://www.tensorflow.org/api_docs/python/tf/strings)。

下面是一个标量字符串张量：

In [56]:
# 张量可以是字符串，这里也是标量(scalar)字符串。
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)

tf.Tensor(b'Gray wolf', shape=(), dtype=string)


下面是一个字符串向量：

<table>
<tr>
  <th>字符串向量，形状：<code>[3,]</code> </th>
</tr>
<tr>
  <td> <img src="https://tensorflow.google.cn/guide/images/tensor/strings.png" alt="The string length is not one of the tensor's axes."> </td>
</tr>
</table>

In [57]:
# 如果我们有三个不同长度的字符串张量，这是可以的。
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])
# 请注意，形状为 (3,)。不包括字符串长度。
print(tensor_of_strings)

tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)


在上面的打印输出中，`b` 前缀表示 `tf.string` dtype 不是 Unicode 字符串，而是字节字符串。有关在 TensorFlow 如何使用 Unicode 文本的详细信息，请参阅 [Unicode 教程](https://tensorflow.google.cn/tutorials/load_data/unicode)。

如果传递 Unicode 字符，则会使用 utf-8 编码。

In [58]:
tf.constant("🥳👍")

<tf.Tensor: shape=(), dtype=string, numpy=b'\xf0\x9f\xa5\xb3\xf0\x9f\x91\x8d'>

在 `tf.strings` 中可以找到用于操作字符串的一些基本函数，包括 `tf.strings.split`。

In [59]:
# 我们可以使用 split 将字符串拆分为一组张量
print(tf.strings.split(scalar_string_tensor, sep=" "))

tf.Tensor([b'Gray' b'wolf'], shape=(2,), dtype=string)


In [60]:
# ...但是如果我们拆分字符串的张量，它就会变成“不规则张量(RaggedTensor)”,
# 因为每个字符串可能被分成不同数量的部分。
print(tf.strings.split(tensor_of_strings))

<tf.RaggedTensor [[b'Gray', b'wolf'], [b'Quick', b'brown', b'fox'], [b'Lazy', b'dog']]>


<table>
<tr>
  <th>三个字符串分割，形状：<code>[3, None]</code> </th>
</tr>
<tr>
  <td> <img src="https://tensorflow.google.cn/guide/images/tensor/string-split.png" alt="Splitting multiple strings returns a tf.RaggedTensor"> </td>
</tr>
</table>

以及 `tf.string.to_number`：

In [61]:
text = tf.constant("1 10 100")
print(tf.strings.to_number(tf.strings.split(text, " ")))

tf.Tensor([  1.  10. 100.], shape=(3,), dtype=float32)


虽然不能使用 `tf.cast` 将字符串张量转换为数值，但是可以先将其转换为字节，然后转换为数值。

In [63]:
byte_strings = tf.strings.bytes_split(tf.constant("Duck"))
byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8)
print("字节串(Byte strings):", byte_strings)
print("字节(Bytes):", byte_ints)

字节串(Byte strings): tf.Tensor([b'D' b'u' b'c' b'k'], shape=(4,), dtype=string)
字节(Bytes): tf.Tensor([ 68 117  99 107], shape=(4,), dtype=uint8)


In [64]:
# 或将其拆分为 unicode，然后对其进行解码
unicode_bytes = tf.constant("アヒル 🦆")
unicode_char_bytes = tf.strings.unicode_split(unicode_bytes, "UTF-8")
unicode_values = tf.strings.unicode_decode(unicode_bytes, "UTF-8")

print("\nUnicode bytes:", unicode_bytes)
print("\nUnicode chars:", unicode_char_bytes)
print("\nUnicode values:", unicode_values)


Unicode bytes: tf.Tensor(b'\xe3\x82\xa2\xe3\x83\x92\xe3\x83\xab \xf0\x9f\xa6\x86', shape=(), dtype=string)

Unicode chars: tf.Tensor([b'\xe3\x82\xa2' b'\xe3\x83\x92' b'\xe3\x83\xab' b' ' b'\xf0\x9f\xa6\x86'], shape=(5,), dtype=string)

Unicode values: tf.Tensor([ 12450  12498  12523     32 129414], shape=(5,), dtype=int32)


`tf.string` dtype 可用于 TensorFlow 中的所有原始字节数据。[`tf.io`](https://www.tensorflow.org/api_docs/python/tf/io) 模块包含在数据与字节类型之间进行相互转换的函数，包括解码图像和解析 csv 的函数。

## 稀疏张量

在某些情况下，数据很稀疏，比如说在一个非常宽的嵌入空间中。为了高效存储稀疏数据，TensorFlow 支持 [`tf.sparse.SparseTensor`](https://www.tensorflow.org/api_docs/python/tf/sparse/SparseTensor) 和相关运算。

<table>
<tr>
  <th>“tf.SparseTensor”，形状：<code>[3, 4]</code> </th>
</tr>
<tr>
  <td> <img src="https://tensorflow.google.cn/guide/images/tensor/sparse.png" alt="An 3x4 grid, with values in only two of the cells."> </td>
</tr>
</table>

In [65]:
# 稀疏张量(Sparse Tensor)以内存高效(memory-efficient)的方式按索引存储值
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# 我们可以将稀疏张量转换为密集张量(dense)
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
